name: AlgoTrader

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: RB checkout algotrader repo
        uses: actions/checkout@v3
      - name: RB setup python v3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: RB install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: RB run python test script
        run: ./praxis.py
