name: AlgoTrader

on: workflow_dispatch

jobs:
  screen:
    runs-on: ubuntu-latest
    steps:
      - name: checkout algotrader repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: run python script
        run: praxis.py
